import { useState } from 'react';
import './App.css';
import questions from './data/questions';
console.log(questions);

function App() {
  const [results, setResults] = useState([]);
  console.log(results);
  const handleSubmit = (event) => {
    event.preventDefault();

    const newResults = [];

    // loop over all questions
    questions.forEach((question, index) => {
      // select all input elements that belong to this question
      const inputs = document.querySelectorAll(`input[name="${index}"]`);

      // loop over all inputs and check if they are checked
      inputs.forEach((input) => {
        if (input.checked) {
          // check if the selected answer is correct
          const isCorrect = input.value === String(true);

          // add a class to the input based on the result
          input.parentElement.classList.add(
            isCorrect ? 'correct' : 'incorrect'
          );

          // add the result to the array of results
          newResults.push({ question: question.question, isCorrect });
        }
      });
    });

    // update the results state
    setResults(newResults);
  };

  return (
    <>
      <h1>SAP Project Systems Certification Quiz</h1>
      <div className='warning-wrapper'>
        <p className='warning'>
          This are not questions from the actul certification exam these
          quesitons have been generated by myself in order to learn faster and
          maybe help someone else prepare better for exam!
        </p>
        <span className='top'></span>
        <span className='right'></span>
        <span className='bottom'></span>
        <span className='left'></span>
      </div>
      <form onSubmit={handleSubmit}>
        <ol>
          {questions.map((question, index) => (
            <li key={index}>
              <h3>{question.question}</h3>
              {question.options.map((option, optionIndex) => {
                if (
                  question.type === 'true_false' ||
                  question.type === 'multiple_choice'
                ) {
                  return (
                    <div key={optionIndex}>
                      <label>
                        <input type='radio' name={index} value={option.value} />{' '}
                        {option.option}{' '}
                      </label>
                    </div>
                  );
                } else if (question.type === 'multiple_right_answers') {
                  return (
                    <div key={optionIndex}>
                      <label>
                        <input
                          type='checkbox'
                          name={index}
                          value={option.value}
                        />
                        {option.option}
                      </label>
                    </div>
                  );
                }
              })}
            </li>
          ))}
        </ol>
        <div className='button-wrapper'>
          <button type='submit' value='Submit'>
            SUBMIT
          </button>
        </div>
      </form>
    </>
  );
}

export default App;
